#!/usr/bin/env bash
# Script that will display information about subdomains.
# Takes 2 arguments, domain and subdomain

display_info() {
	dig $1 | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ $# -eq 2 ]; then
	display_info "$2.$1" "$2"
else
	display_info "www.$1" "www"
	display_info "lb-01.$1" "lb-01"
	display_info "web-01.$1" "web-01"
	display_info "web-02.$1" "web-02"
fi
