#!/usr/bin/env bash
# Install nginx on your web-01 server
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
# Setup Index html file
mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" >/var/www/html/index.html
# Setup 404 html file
echo "Ceci n'est pas une page" >/var/www/html/404.html
# Setup Nginx Config File
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" >/etc/nginx/sites-available/default
# Restart the nginx server
service nginx restart
