#!/usr/bin/env bash

# Update packages
apt-get -y update
apt-get -y upgrade

# Add HAProxy PPA
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y update

# Install HAProxy
apt-get -y install haproxy=2.8.\*

# Backup original config file
cp -a /etc/haproxy/haproxy.cfg{,.orig}

# Setup config file
printf %s "
frontend myfrontend
  mode http
  bind :80
  default_backend web_servers

backend web_servers
  balance roundrobin
  server 427439-web-01 100.25.33.139:80 check
  server 427439-web-02 54.146.73.237:80 check
" >/etc/haproxy/haproxy.cfg

# Start the server
service haproxy restart
