#!/usr/bin/env bash
# Load balancer setup file

balancer="
frontend my_frontend
    mode http
    bind :80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 427439-web-01 54.174.43.223:80 check
    server 427439-web-02 18.235.255.170:80 check
"

# Update packages
apt-get -y update
apt-get -y upgrade

# Add HAProxy PPA
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# Install HAProxy
apt-get -y install haproxy

# Backup original config file
cp -a /etc/haproxy/haproxy.cfg{,.orig}

# Setup config file
echo "$balancer" >>/etc/haproxy/haproxy.cfg

# Start the server
service haproxy restart
