#!/usr/bin/env bash
# This script is printing "Best School" 10 times to the std output
hour=0

while [ $hour -le 12 ]; do 
  miniute=0
  while [[ $miniute -le 59 ]]; do
    echo $miniute
    ((miniute++))
  done
  echo "Hour: $hour"
  ((hour++))
done
