#!/usr/bin/env bash
# This script is printing "Best School" 10 times to the std output
i=0

while [ $i -lt 10 ];
do 
  if [[ $i -ne 8 ]]; then
    echo "Best School"
  else
    echo "Hi"
  fi
  ((i++))
done
