#!/usr/bin/env bash
# This script is printing "Best School" 10 times to the std output
result=$(file -b school)
if test -e school; then
  echo "school file exists"
  if ! [ -s school ]; then
    echo "school file is empty"
  else
    echo "school file is not empty"
    if test -f school; then
      echo "school is a regular file"
    fi
  fi
else
  echo "school file does not exist"
fi
