#!/usr/bin/env bash
#Script that configures an Ubuntu server with the below requirements.
#Requirements:
#    localhost resolves to 127.0.0.2
#    facebook.com resolves to 8.8.8.8.
mv /etc/hosts /etc/hosts.old
echo "127.0.0.2 localhost" > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
