#!/usr/bin/env bash
#Bash script that displays all active IPv4 IPs on the machine it’s executed on.
flag=0
for line in $(ifconfig)
do
  if [[ $flag -eq 1 ]]; then
    echo "$line"
    flag=0
  fi
  if [[ $line == "inet" ]]; then
    flag=1
  fi
done
